repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: mixed-line-ending
      - id: check-executables-have-shebangs

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: ^frontend/
        types_or: [javascript, jsx, ts, tsx, json, css, scss, markdown]
        args: ['--config', 'frontend/.prettierrc', '--ignore-path', 'frontend/.prettierignore']
        additional_dependencies:
          - prettier@3.6.2

  - repo: local
    hooks:
      - id: eslint
        name: ESLint
        entry: bash -c 'cd frontend && npx eslint src --ext .ts,.tsx,.js,.jsx --config .eslintrc.json --fix --max-warnings=0'
        language: system
        files: ^frontend/src/.*\.(js|jsx|ts|tsx)$
        require_serial: true
        pass_filenames: false

      - id: typescript-check
        name: TypeScript Check
        entry: bash -c 'cd frontend && npx tsc --noEmit'
        language: system
        files: ^frontend/src/.*\.(ts|tsx)$
        require_serial: true
        # Compile the full project instead of just the touched files
        pass_filenames: false

      - id: type-coverage
        name: Type Coverage Check
        entry: bash -c 'cd frontend && npx type-coverage --at-least 95'
        language: system
        files: ^frontend/src/.*\.(ts|tsx)$
        require_serial: true
        pass_filenames: false
