repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: mixed-line-ending
      - id: check-executables-have-shebangs

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: ^frontend/
        types_or: [javascript, jsx, ts, tsx, json, css, scss, markdown]
        args: ['--config', 'frontend/.prettierrc', '--ignore-path', 'frontend/.prettierignore']
        additional_dependencies:
          - prettier@3.6.2

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: ^frontend/src/.*\.(js|jsx|ts|tsx)$
        language: node
        args: ['--config', 'frontend/.eslintrc.json', '--fix', '--max-warnings=0']
        additional_dependencies:
          - eslint@8.56.0
          - '@typescript-eslint/eslint-plugin@5.62.0'
          - '@typescript-eslint/parser@5.62.0'
          - 'eslint-config-prettier@9.1.0'
          - 'eslint-config-react-app@7.0.1'
          - 'eslint-import-resolver-typescript@3.6.1'
          - 'eslint-plugin-import@2.29.1'
          - 'eslint-plugin-jsx-a11y@6.8.0'
          - 'eslint-plugin-prettier@5.1.0'
          - 'eslint-plugin-react@7.33.2'
          - 'eslint-plugin-react-hooks@4.6.0'
          - 'prettier@3.6.2'

  - repo: local
    hooks:
      - id: typescript-check
        name: TypeScript Check
        entry: npx tsc --noEmit
        language: system
        types: [ts, tsx]
        require_serial: true
        # Compile the full project instead of just the touched files
        pass_filenames: false

      - id: type-coverage
        name: Type Coverage Check
        entry: npx type-coverage --at-least 95
        language: system
        types: [ts, tsx]
        require_serial: true
        pass_filenames: false
