version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: carolinas_diary_postgres
    environment:
      POSTGRES_DB: carolinas_diary
      POSTGRES_USER: diary_user
      POSTGRES_PASSWORD: diary_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U diary_user -d carolinas_diary"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: carolinas_diary_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@carolinasdiary.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data: