repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        files: ^backend/
        exclude: ^backend/venv/
      - id: end-of-file-fixer
        files: ^backend/
        exclude: ^backend/venv/
      - id: check-yaml
        files: ^backend/
        exclude: ^backend/venv/
      - id: check-added-large-files
      - id: check-json
        files: ^backend/
        exclude: ^backend/venv/
      - id: check-toml
        files: ^backend/
        exclude: ^backend/venv/
      - id: check-xml
        files: ^backend/
        exclude: ^backend/venv/
      - id: debug-statements
        files: ^backend/.*\.py$
        exclude: ^backend/venv/
      - id: check-builtin-literals
        files: ^backend/.*\.py$
        exclude: ^backend/venv/
      - id: check-case-conflict
      - id: check-docstring-first
        files: ^backend/.*\.py$
        exclude: ^backend/venv/
      - id: check-merge-conflict
      - id: check-executables-have-shebangs

  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        language_version: python3
        files: ^backend/.*\.py$
        exclude: ^backend/venv/

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args:
          - --profile=black
        files: ^backend/.*\.py$
        exclude: ^backend/venv/

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args:
          - --max-line-length=88
          - --extend-ignore=E203,W503
        files: ^backend/.*\.py$
        exclude: ^backend/venv/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        files: ^backend/.*\.py$
        exclude: ^backend/venv/
        additional_dependencies:
          - types-requests
          - types-python-dateutil
          - types-setuptools
          - sqlalchemy[mypy]==2.0.23
          - pydantic[email]==2.5.0
          - fastapi>=0.116.1
          - python-multipart>=0.0.18
        args: [
          --python-version=3.11,
          --ignore-missing-imports,
          --disallow-untyped-defs,
          --disallow-incomplete-defs,
          --check-untyped-defs,
          --warn-return-any,
          --warn-unused-ignores,
          --show-error-codes,
          --exclude=venv/
        ]

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args:
          - --severity-level=medium
          - --exclude=tests/
        files: ^backend/.*\.py$
        exclude: ^backend/venv/

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.2
    hooks:
      - id: python-safety-dependencies-check
        files: ^backend/requirements.*\.txt$
